# Generated by Django 6.0.6 on 2026-08-03 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador')], default='ESTUDIANTE', help_text='Se calcula solo: el de mayor alcance entre los perfiles de la persona.', max_length=20, verbose_name='rol principal'),
        ),
        migrations.CreateModel(
            name='RolAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante'), ('COORDINADOR', 'Coordinador')], max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_adicionales', to='core.perfilusuario')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil adicional',
                'verbose_name_plural': 'perfiles adicionales',
                'ordering': ['rol'],
                'unique_together': {('perfil', 'rol')},
            },
        ),
    ]
