# Generated by Django 6.0.6 on 2026-08-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_rol_roladicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='institucion',
        ),
        migrations.DeleteModel(
            name='Institucion',
        ),
    ]
