# Generated by Django 5.2.15 on 2026-08-08 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_perfilusuario_institucion_delete_institucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roladicional',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', help_text='Rol principal de la persona. Se calcula según la precedencia de sus perfiles.', max_length=20, verbose_name='rol principal'),
        ),
        migrations.AlterField(
            model_name='roladicional',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COORDINADOR', 'Coordinador'), ('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='roladicional',
            constraint=models.UniqueConstraint(fields=('perfil', 'rol'), name='uq_perfil_rol_adicional'),
        ),
    ]
