# Generated by Django 6.0.6 on 2026-06-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='duracion_periodos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='carrera',
            name='titulo_otorga',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
