# Generated by Django 6.0.6 on 2026-06-13 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_carrera_duracion_periodos_carrera_modalidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SilaboMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True)),
                ('resultados_aprendizaje', models.JSONField(blank=True, default=list)),
                ('competencias', models.JSONField(blank=True, default=list)),
                ('unidades', models.JSONField(blank=True, default=list)),
                ('metodologia', models.TextField(blank=True)),
                ('evidencias', models.JSONField(blank=True, default=list)),
                ('bibliografia', models.TextField(blank=True)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silabos', to='academico.materiamalla')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='silabos', to='academico.periodoacademico')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['periodo', 'materia_malla__nivel__numero', 'materia_malla__orden'],
                'unique_together': {('materia_malla', 'periodo')},
            },
        ),
    ]
