# Generated by Django 6.0.6 on 2026-06-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_silabomateria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SilaboMateria',
        ),
    ]
