# Generated by Django 6.0.6 on 2026-08-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_delete_silabomateria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaMallaPredecesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecesoras', to='academico.materiamalla')),
                ('predecesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras', to='academico.materiamalla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'predecesora',
                'verbose_name_plural': 'predecesoras',
                'ordering': ['materia_malla__nivel__numero', 'materia_malla__materia__nombre'],
                'unique_together': {('materia_malla', 'predecesora')},
            },
        ),
        migrations.CreateModel(
            name='NivelPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('paralelo', models.CharField(default='A', max_length=20)),
                ('cupo', models.PositiveIntegerField(default=30)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_CURSO', 'En curso'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='academico.nivelmalla')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveles_periodo', to='academico.periodoacademico')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'oferta de nivel',
                'verbose_name_plural': 'ofertas de nivel',
                'ordering': ['-periodo__fecha_inicio', 'nivel__malla__nombre', 'nivel__numero', 'paralelo'],
                'unique_together': {('periodo', 'nivel', 'paralelo')},
            },
        ),
        migrations.CreateModel(
            name='RecordAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_academico', to=settings.AUTH_USER_MODEL)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='academico.materiamalla')),
                ('periodo', models.ForeignKey(blank=True, help_text='Periodo en que la aprobo o reprobo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='academico.periodoacademico')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'record academico',
                'verbose_name_plural': 'records academicos',
                'ordering': ['estudiante', 'materia_malla__nivel__numero'],
                'unique_together': {('estudiante', 'materia_malla')},
            },
        ),
    ]
