# Generated by Django 6.0.6 on 2026-08-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_niveles_periodo_sin_repetir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelperiodo',
            options={'ordering': ['-periodo__fecha_inicio', 'nivel__malla__nombre', 'nivel__numero'], 'verbose_name': 'nivel habilitado en el periodo', 'verbose_name_plural': 'niveles habilitados en el periodo'},
        ),
        migrations.AlterUniqueTogether(
            name='nivelperiodo',
            unique_together={('periodo', 'nivel')},
        ),
        migrations.RemoveField(
            model_name='nivelperiodo',
            name='cupo',
        ),
        migrations.RemoveField(
            model_name='nivelperiodo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='nivelperiodo',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='nivelperiodo',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='nivelperiodo',
            name='paralelo',
        ),
    ]
