# Generated by Django 6.0.6 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_alter_nivelperiodo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelperiodo',
            options={'ordering': ['-periodo__fecha_inicio', 'nivel__malla__nombre', 'nivel__numero'], 'verbose_name': 'nivel del periodo', 'verbose_name_plural': 'niveles del periodo'},
        ),
        migrations.AddField(
            model_name='nivelperiodo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Como se llama este nivel en el periodo. Si lo dejas vacio se usa el de la malla.', max_length=150),
        ),
    ]
