# Generated by Django 6.0.6 on 2026-08-06 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0010_delete_nivelperiodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('malla_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='academico.mallaperiodo')),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_periodo', to='academico.materiamalla', verbose_name='asignatura de la malla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'materia del periodo',
                'verbose_name_plural': 'materias del periodo',
                'ordering': ['malla_periodo', 'materia_malla__nivel__numero', 'materia_malla__orden', 'materia_malla__materia__nombre'],
                'unique_together': {('malla_periodo', 'materia_malla')},
            },
        ),
    ]
