# Generated by Django 6.0.6 on 2026-08-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0011_materiaperiodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recordacademico',
            options={'ordering': ['estudiante', 'materia_malla__nivel__numero'], 'verbose_name': 'record académico', 'verbose_name_plural': 'records académicos'},
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='institucion',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='inscripcionmalla',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activa'), (2, 'Retirada'), (3, 'Finalizada')], default=1),
        ),
        migrations.AlterField(
            model_name='mallaperiodo',
            name='nombre',
            field=models.CharField(blank=True, help_text='Cómo se llama esta malla en el periodo. Si lo dejas vacío se usa el nombre de la malla.', max_length=150),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='recordacademico',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Periodo en que la aprobó o reprobó.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='academico.periodoacademico'),
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='institucion',
        ),
    ]
