# Generated by Django 5.2.15 on 2026-08-08 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0014_carrera_modalidad_a_catalogo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mallaperiodo',
            unique_together={('periodo', 'malla', 'nombre')},
        ),
    ]
