# Generated by Django 5.2.15 on 2026-08-08 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0015_alter_mallaperiodo_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recordacademico',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recordacademico',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='recordacademico',
            name='materia_malla',
        ),
        migrations.RemoveField(
            model_name='recordacademico',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='recordacademico',
            name='usuario_creacion',
        ),
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre'], 'verbose_name': 'carrera', 'verbose_name_plural': 'carreras'},
        ),
        migrations.AlterModelOptions(
            name='inscripcionmalla',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'inscripción en malla', 'verbose_name_plural': 'inscripciones en malla'},
        ),
        migrations.AlterModelOptions(
            name='malla',
            options={'ordering': ['carrera__nombre', 'nombre'], 'verbose_name': 'malla', 'verbose_name_plural': 'mallas'},
        ),
        migrations.AlterModelOptions(
            name='mallaperiodo',
            options={'ordering': ['periodo', 'malla__nombre', 'nombre'], 'verbose_name': 'malla en el periodo', 'verbose_name_plural': 'mallas en el periodo'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AlterModelOptions(
            name='materiamalla',
            options={'ordering': ['malla', 'nivel__numero', 'orden', 'materia__nombre'], 'verbose_name': 'materia de malla', 'verbose_name_plural': 'materias de malla'},
        ),
        migrations.AlterModelOptions(
            name='materiamallapredecesora',
            options={'ordering': ['materia_malla__nivel__numero', 'materia_malla__materia__nombre', 'predecesora__nivel__numero'], 'verbose_name': 'materia predecesora', 'verbose_name_plural': 'materias predecesoras'},
        ),
        migrations.AlterModelOptions(
            name='nivelmalla',
            options={'ordering': ['malla', 'numero'], 'verbose_name': 'nivel de malla', 'verbose_name_plural': 'niveles de malla'},
        ),
        migrations.AlterModelOptions(
            name='periodoacademico',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'periodo', 'verbose_name_plural': 'periodos'},
        ),
        migrations.AlterModelOptions(
            name='profesormateria',
            options={'ordering': ['materia_malla__malla__nombre', 'materia_malla__nivel__numero', 'materia_malla__materia__nombre', 'profesor__last_name', 'profesor__first_name'], 'verbose_name': 'profesor de materia', 'verbose_name_plural': 'profesores de materias'},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionmalla',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='malla',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mallaperiodo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materiamalla',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materiamallapredecesora',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='materiaperiodo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='nivelmalla',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='profesormateria',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='activo_matricula',
        ),
        migrations.AddField(
            model_name='inscripcionmalla',
            name='malla_periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.mallaperiodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materiaperiodo',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='materias_como_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mallaperiodo',
            name='malla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mallas_periodo', to='academico.malla'),
        ),
        migrations.AlterField(
            model_name='materiamalla',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_malla', to='academico.materia'),
        ),
        migrations.AlterField(
            model_name='materiaperiodo',
            name='materia_malla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_periodo', to='academico.materiamalla', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modalidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='nivelmalla',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profesormateria',
            name='materia_malla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='academico.materiamalla'),
        ),
        migrations.AlterField(
            model_name='profesormateria',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesor_materias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='inscripcionmalla',
            constraint=models.UniqueConstraint(fields=('estudiante', 'malla_periodo'), name='uq_estudiante_malla_periodo'),
        ),
        migrations.AddConstraint(
            model_name='malla',
            constraint=models.UniqueConstraint(fields=('carrera', 'codigo'), name='uq_malla_carrera_codigo'),
        ),
        migrations.AddConstraint(
            model_name='mallaperiodo',
            constraint=models.UniqueConstraint(fields=('periodo', 'malla', 'nombre'), name='uq_periodo_malla_nombre'),
        ),
        migrations.AddConstraint(
            model_name='materiamalla',
            constraint=models.UniqueConstraint(fields=('malla', 'materia'), name='uq_malla_materia'),
        ),
        migrations.AddConstraint(
            model_name='materiamallapredecesora',
            constraint=models.UniqueConstraint(fields=('materia_malla', 'predecesora'), name='uq_materia_predecesora'),
        ),
        migrations.AddConstraint(
            model_name='materiaperiodo',
            constraint=models.UniqueConstraint(fields=('malla_periodo', 'materia_malla'), name='uq_materia_periodo'),
        ),
        migrations.AddConstraint(
            model_name='nivelmalla',
            constraint=models.UniqueConstraint(fields=('malla', 'numero'), name='uq_malla_nivel'),
        ),
        migrations.AddConstraint(
            model_name='profesormateria',
            constraint=models.UniqueConstraint(fields=('profesor', 'materia_malla'), name='uq_profesor_materia_malla'),
        ),
        migrations.DeleteModel(
            name='RecordAcademico',
        ),
        migrations.RemoveField(
            model_name='inscripcionmalla',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='inscripcionmalla',
            name='malla',
        ),
        migrations.RemoveField(
            model_name='inscripcionmalla',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='profesormateria',
            name='fecha_asignacion',
        ),
        migrations.RemoveField(
            model_name='profesormateria',
            name='periodo',
        ),
    ]
