# Generated by Django 6.0.6 on 2026-06-17 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0020_eventosimulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionsugeridasimulacion',
            name='costo_recursos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='intento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintentos', to='simulador.intentosimulacion'),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='recursos_actuales',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='costo_recursos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='recursos_antes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='recursos_despues',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PistaTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_ronda', models.PositiveIntegerField(default=1)),
                ('pregunta_estudiante', models.TextField(blank=True, default='')),
                ('pista', models.TextField()),
                ('conceptos_referidos', models.JSONField(blank=True, default=list)),
                ('usada', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas_tutor', to='simulador.intentosimulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['intento', 'numero_ronda', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecursoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('es_critico', models.BooleanField(default=False)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'nombre'],
                'unique_together': {('simulacion', 'codigo')},
            },
        ),
    ]
