# Generated by Django 6.0.6 on 2026-08-07 01:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0012_alter_recordacademico_options_and_more'),
        ('simulador', '0051_remove_asignacion_guia_api_remove_seccion_cupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('motor', models.CharField(db_index=True, max_length=80)),
                ('motor_version', models.CharField(default='1.0.0', max_length=20)),
                ('titulo', models.CharField(max_length=250)),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('puntaje_minimo', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('intentos_permitidos', models.PositiveIntegerField(default=0, help_text='Cero significa intentos ilimitados.')),
                ('tiempo_limite_segundos', models.PositiveIntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('publicada', models.BooleanField(default=False)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_interactivas_creadas', to=settings.AUTH_USER_MODEL)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_interactivas', to='academico.materiamalla')),
                ('simulacion', models.ForeignKey(blank=True, help_text='Si se elige un caso, el juego se exige antes de empezarlo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_interactivas', to='simulador.simulacion')),
                ('tema', models.ForeignKey(blank=True, help_text='Vacio cuando el juego abarca toda la materia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_interactivas', to='simulador.temamateria')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actividad interactiva',
                'verbose_name_plural': 'actividades interactivas',
                'ordering': ['materia_malla', 'tema__orden', 'orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='IntentoActividadInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_intento', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('APROBADO', 'Aprobado'), ('NO_APROBADO', 'No aprobado'), ('ABANDONADO', 'Abandonado')], default='EN_PROCESO', max_length=20)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tiempo_segundos', models.PositiveIntegerField(default=0)),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aciertos', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('total_elementos', models.PositiveIntegerField(default=0)),
                ('completado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('detalle_resultado', models.JSONField(blank=True, default=dict)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='interactivo.actividadinteractiva')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_actividades_interactivas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EventoActividadInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('verbo', models.CharField(max_length=50)),
                ('elemento_id', models.CharField(blank=True, default='', max_length=120)),
                ('tiempo_segundos', models.PositiveIntegerField(default=0)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='interactivo.intentoactividadinteractiva')),
            ],
            options={
                'ordering': ['fecha_creacion', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RecursoActividadInteractiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='interactivo/recursos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='interactivo.actividadinteractiva')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['actividad', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='intentoactividadinteractiva',
            constraint=models.UniqueConstraint(fields=('actividad', 'estudiante', 'numero_intento'), name='intento_interactivo_numero_unico'),
        ),
    ]
