from django.contrib import admin

from .models import (
    AccionSugeridaSimulacion,
    ActividadMateria,
    Asignacion,
    CondicionExitoSimulacion,
    ConceptoEsperadoRonda,
    CriterioEvaluacion,
    DecisionConfigurada,
    EscenarioSimulacion,
    EventoSimulacion,
    IndicadorSimulacion,
    IntentoSimulacion,
    MatrizEvaluacionCaso,
    OpcionCasoSimulacion,
    PasoSimulacion,
    PerfilMateriaIA,
    PlantillaConcepto,
    PlantillaIndicador,
    PlantillaRestriccion,
    PlantillaRonda,
    PlantillaSimulacion,
    PistaTutor,
    Equipo,
    RecursoSimulacion,
    ResultadoAprendizaje,
    RestriccionSimulacion,
    Seccion,
    Simulacion,
    TemaMateria,
)

admin.site.register(Simulacion)
admin.site.register(TemaMateria)
admin.site.register(ActividadMateria)
admin.site.register(PerfilMateriaIA)
admin.site.register(PlantillaSimulacion)
admin.site.register(PlantillaRonda)
admin.site.register(PlantillaIndicador)
admin.site.register(PlantillaRestriccion)
admin.site.register(PlantillaConcepto)
admin.site.register(IndicadorSimulacion)
admin.site.register(RecursoSimulacion)
admin.site.register(RestriccionSimulacion)
admin.site.register(CriterioEvaluacion)
admin.site.register(MatrizEvaluacionCaso)
admin.site.register(OpcionCasoSimulacion)
admin.site.register(AccionSugeridaSimulacion)
admin.site.register(CondicionExitoSimulacion)
admin.site.register(EventoSimulacion)
admin.site.register(ConceptoEsperadoRonda)
admin.site.register(EscenarioSimulacion)
admin.site.register(DecisionConfigurada)
admin.site.register(IntentoSimulacion)
admin.site.register(PasoSimulacion)
admin.site.register(PistaTutor)
admin.site.register(ResultadoAprendizaje)
admin.site.register(Seccion)
admin.site.register(Asignacion)
admin.site.register(Equipo)
