# Generated by Django 6.0.6 on 2026-06-13 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=250)),
                ('consecuencia', models.TextField()),
                ('retroalimentacion', models.TextField(blank=True)),
                ('impacto', models.JSONField(default=dict)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='simulador.escenario')),
            ],
            options={
                'ordering': ['escenario', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivo_aprendizaje', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada'), ('ARCHIVADA', 'Archivada')], default='BORRADOR', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones', to='academico.materiamalla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['materia_malla__materia__nombre', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='IntentoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado_actual', models.JSONField(blank=True, default=dict)),
                ('retroalimentacion_final', models.TextField(blank=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_simulacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='simulador.simulacion')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='escenario',
            name='simulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='simulador.simulacion'),
        ),
        migrations.CreateModel(
            name='DecisionTomada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('justificacion', models.TextField(blank=True)),
                ('estado_resultante', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tomadas', to='simulador.decision')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisiones_tomadas', to='simulador.escenario')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_tomadas', to='simulador.intentosimulacion')),
            ],
            options={
                'ordering': ['fecha'],
                'unique_together': {('intento', 'escenario')},
            },
        ),
        migrations.CreateModel(
            name='IndicadorSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('clave', models.SlugField(max_length=80)),
                ('valor_inicial', models.FloatField(default=0)),
                ('minimo', models.FloatField(blank=True, null=True)),
                ('maximo', models.FloatField(blank=True, null=True)),
                ('unidad', models.CharField(blank=True, max_length=30)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='simulador.simulacion')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('simulacion', 'clave')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='escenario',
            unique_together={('simulacion', 'orden')},
        ),
    ]
