# Generated by Django 6.0.6 on 2026-06-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='contexto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='ia_habilitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='prompt_ia_base',
            field=models.TextField(blank=True),
        ),
    ]
