# Generated by Django 6.0.6 on 2026-06-13 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_silabomateria'),
        ('simulador', '0002_simulacion_contexto_simulacion_ia_habilitada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='codigo',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='es_critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='valor_maximo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='valor_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intentos_simulacion', to='academico.periodoacademico'),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='puntuacion_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='instrucciones_ia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='maximo_decisiones',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='nivel_dificultad',
            field=models.CharField(choices=[('BASICO', 'Basico'), ('MEDIO', 'Medio'), ('AVANZADO', 'Avanzado')], default='MEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='objetivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='resultado_aprendizaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='rol_estudiante',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tema',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AccionSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('impacto_base', models.JSONField(blank=True, default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'texto'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('peso', models.PositiveIntegerField(default=0)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RestriccionSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_indicador', models.SlugField(max_length=80)),
                ('operador', models.CharField(choices=[('<', 'Menor que'), ('<=', 'Menor o igual'), ('>', 'Mayor que'), ('>=', 'Mayor o igual'), ('==', 'Igual')], max_length=5)),
                ('valor_limite', models.FloatField()),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'codigo_indicador'],
            },
        ),
        migrations.CreateModel(
            name='PasoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('situacion_presentada', models.TextField()),
                ('decision_estudiante', models.TextField()),
                ('justificacion_estudiante', models.TextField()),
                ('evaluacion_ia', models.TextField(blank=True)),
                ('impacto_calculado', models.JSONField(blank=True, default=dict)),
                ('estado_antes', models.JSONField(blank=True, default=dict)),
                ('estado_despues', models.JSONField(blank=True, default=dict)),
                ('puntaje_paso', models.FloatField(default=0)),
                ('alertas_restricciones', models.JSONField(blank=True, default=list)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='simulador.intentosimulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['intento', 'numero'],
                'unique_together': {('intento', 'numero')},
            },
        ),
    ]
