# Generated by Django 6.0.6 on 2026-06-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0003_indicadorsimulacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='ia_habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
