# Generated by Django 6.0.6 on 2026-06-13 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_alter_simulacion_ia_habilitada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionsimulacion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='indicadorsimulacion',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='indicadorsimulacion',
            name='maximo',
        ),
        migrations.RemoveField(
            model_name='indicadorsimulacion',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='objetivo_aprendizaje',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='prompt_ia_base',
        ),
        migrations.RemoveField(
            model_name='simulacion',
            name='publicada',
        ),
        migrations.DeleteModel(
            name='DecisionTomada',
        ),
    ]
