# Generated by Django 6.0.6 on 2026-06-13 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_clave_a_codigo(apps, schema_editor):
    IndicadorSimulacion = apps.get_model('simulador', 'IndicadorSimulacion')
    for ind in IndicadorSimulacion.objects.all():
        if ind.codigo:
            continue
        ind.codigo = getattr(ind, 'clave', '') or ind.nombre.lower().replace(' ', '_')
        ind.save(update_fields=['codigo'])


def copiar_tema_y_descripcion(apps, schema_editor):
    Simulacion = apps.get_model('simulador', 'Simulacion')
    for s in Simulacion.objects.all():
        if not s.situacion_inicial and s.contexto:
            s.situacion_inicial = s.contexto[:300]
            s.save(update_fields=['situacion_inicial'])


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_remove_accionsimulacion_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='escenario',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='usuario_creacion',
        ),
        migrations.AlterUniqueTogether(
            name='escenario',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='escenario',
            name='simulacion',
        ),
        migrations.RemoveField(
            model_name='escenario',
            name='usuario_creacion',
        ),
        migrations.AddField(
            model_name='criterioevaluacion',
            name='puntaje_maximo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='codigo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RunPython(
            copiar_clave_a_codigo, reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='debriefing_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='nivel_resultado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='penalizacion_aplicada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='puntaje_ia_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='siguiente_situacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restriccionsimulacion',
            name='penalizacion',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='guia_debriefing',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='nivel_ayuda_ia',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='retroalimentacion_base',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='situacion_inicial',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tiempo_estimado',
            field=models.IntegerField(default=30, help_text='Tiempo estimado en minutos'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tono_retroalimentacion',
            field=models.CharField(blank=True, default='Formativo y claro', max_length=100),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='criterioevaluacion',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='indicadorsimulacion',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='indicadorsimulacion',
            name='unidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='indicadorsimulacion',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadorsimulacion',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AlterField(
            model_name='indicadorsimulacion',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='intentosimulacion',
            name='puntuacion_final',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='intentosimulacion',
            name='retroalimentacion_final',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pasosimulacion',
            name='evaluacion_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pasosimulacion',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pasosimulacion',
            name='puntaje_paso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='restriccionsimulacion',
            name='codigo_indicador',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restriccionsimulacion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restriccionsimulacion',
            name='operador',
            field=models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '=')], max_length=5),
        ),
        migrations.AlterField(
            model_name='restriccionsimulacion',
            name='valor_limite',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='instrucciones_ia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='maximo_decisiones',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='nivel_dificultad',
            field=models.CharField(choices=[('BASICA', 'Basica'), ('MEDIA', 'Media'), ('AVANZADA', 'Avanzada')], default='MEDIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='rol_estudiante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='tema',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='AccionSugeridaSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('impacto_base', models.JSONField(blank=True, default=dict)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_sugeridas', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'texto'],
            },
        ),
        migrations.CreateModel(
            name='CondicionExitoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('codigo_indicador', models.CharField(max_length=50)),
                ('operador', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '=')], max_length=5)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonificacion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_exito', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'codigo_indicador'],
            },
        ),
        migrations.DeleteModel(
            name='AccionSimulacion',
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.DeleteModel(
            name='Escenario',
        ),
        migrations.AlterUniqueTogether(
            name='indicadorsimulacion',
            unique_together={('simulacion', 'codigo')},
        ),
        migrations.RemoveField(
            model_name='indicadorsimulacion',
            name='clave',
        ),
    ]
