# Generated by Django 6.0.6 on 2026-06-13 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_simulaciones_existentes_a_ia(apps, schema_editor):
    Simulacion = apps.get_model('simulador', 'Simulacion')
    Simulacion.objects.update(tipo_simulacion='CON_IA_DINAMICA')


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_model_updates_with_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacion',
            name='numero_ronda_actual',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='situacion_actual',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tipo_simulacion',
            field=models.CharField(choices=[('SIN_IA_ARBOL', 'Sin IA - Arbol de decisiones'), ('CON_IA_DINAMICA', 'Con IA - Simulacion dinamica')], default='SIN_IA_ARBOL', max_length=30),
        ),
        migrations.RunPython(migrar_simulaciones_existentes_a_ia, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EscenarioSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('situacion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('es_inicial', models.BooleanField(default=False)),
                ('es_final', models.BooleanField(default=False)),
                ('retroalimentacion_final', models.TextField(blank=True, default='')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios_arbol', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DecisionConfigurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('impacto', models.JSONField(blank=True, default=dict)),
                ('puntaje_base', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retroalimentacion', models.TextField(blank=True, default='')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones', to='simulador.escenariosimulacion')),
                ('siguiente_escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_entrada', to='simulador.escenariosimulacion')),
            ],
            options={
                'ordering': ['escenario', 'texto'],
            },
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='escenario_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_actuales', to='simulador.escenariosimulacion'),
        ),
    ]
