# Generated by Django 6.0.6 on 2026-06-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0007_intentosimulacion_numero_ronda_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacion',
            name='intentos_invalidos_actuales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='max_intentos_invalidos_por_ronda',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='es_valido',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='tipo_paso',
            field=models.CharField(choices=[('VALIDO', 'Valido'), ('INVALIDO', 'Invalido')], default='VALIDO', max_length=20),
        ),
    ]
