# Generated by Django 6.0.6 on 2026-06-13 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0008_intentosimulacion_intentos_invalidos_actuales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoEsperadoRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_ronda', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('palabras_clave', models.TextField(help_text='Separar por comas o ingresar una lista JSON.')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impacto_si_cumple', models.JSONField(blank=True, default=dict)),
                ('retroalimentacion_si_cumple', models.TextField(blank=True, default='')),
                ('retroalimentacion_si_falta', models.TextField(blank=True, default='')),
                ('es_critico', models.BooleanField(default=False)),
                ('escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_esperados', to='simulador.escenariosimulacion')),
                ('simulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos_esperados', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'escenario', 'numero_ronda', 'nombre'],
            },
        ),
    ]
