# Generated by Django 6.0.6 on 2026-06-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0009_conceptoesperadoronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorsimulacion',
            name='direccion_optima',
            field=models.CharField(choices=[('ALTO', 'Mejor cuando es alto'), ('BAJO', 'Mejor cuando es bajo')], default='ALTO', help_text='Define si un valor alto o bajo representa un buen desempeno en este indicador.', max_length=10),
        ),
    ]
