# Generated by Django 6.0.6 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0010_indicadorsimulacion_direccion_optima'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasosimulacion',
            name='evaluacion_detalle',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
