# Generated by Django 6.0.6 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0011_pasosimulacion_evaluacion_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptoesperadoronda',
            name='impacto_si_falta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
