# Generated by Django 6.0.6 on 2026-06-14 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_delete_silabomateria'),
        ('simulador', '0012_conceptoesperadoronda_impacto_si_falta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMateriaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('rol_profesional', models.CharField(blank=True, default='', max_length=200)),
                ('enfoque', models.TextField(blank=True, default='')),
                ('competencias', models.JSONField(blank=True, default=list)),
                ('resultados_aprendizaje', models.JSONField(blank=True, default=list)),
                ('temas_clave', models.JSONField(blank=True, default=list)),
                ('conceptos_clave', models.JSONField(blank=True, default=list)),
                ('indicadores_sugeridos', models.JSONField(blank=True, default=list)),
                ('restricciones_contexto', models.TextField(blank=True, default='')),
                ('criterios_calidad', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'perfil IA de materia',
                'verbose_name_plural': 'perfiles IA de materias',
                'ordering': ['materia_malla__materia__nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaConcepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('regla_evaluacion', models.JSONField(blank=True, default=dict)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('impacto_si_cumple', models.JSONField(blank=True, default=dict)),
                ('impacto_si_falta', models.JSONField(blank=True, default=dict)),
                ('retroalimentacion_si_cumple', models.TextField(blank=True, default='')),
                ('retroalimentacion_si_falta', models.TextField(blank=True, default='')),
                ('es_critico', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ronda', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('valor_inicial', models.DecimalField(decimal_places=2, default=50, max_digits=12)),
                ('valor_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=12)),
                ('direccion_optima', models.CharField(default='ALTO', max_length=10)),
                ('es_critico', models.BooleanField(default=False)),
                ('unidad', models.CharField(blank=True, default='pts', max_length=50)),
            ],
            options={
                'ordering': ['plantilla', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaRestriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('codigo_indicador', models.CharField(max_length=50)),
                ('operador', models.CharField(default='>=', max_length=5)),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('penalizacion', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
            ],
            options={
                'ordering': ['plantilla', 'codigo_indicador'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaRonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=150)),
                ('proposito', models.TextField(blank=True, default='')),
                ('consigna_base', models.TextField(blank=True, default='')),
                ('etiqueta_decision', models.CharField(blank=True, default='Decision', max_length=120)),
                ('etiqueta_justificacion', models.CharField(blank=True, default='Justificacion', max_length=120)),
            ],
            options={
                'ordering': ['plantilla', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('GLOBAL', 'Global'), ('MATERIA', 'Por materia')], default='GLOBAL', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('maximo_decisiones', models.PositiveIntegerField(default=3)),
                ('tiempo_estimado', models.PositiveIntegerField(default=30)),
                ('nivel_dificultad', models.CharField(blank=True, default='MEDIA', max_length=20)),
                ('rol_base', models.CharField(blank=True, default='Responsable de decision', max_length=200)),
                ('contexto_base', models.TextField(blank=True, default='')),
                ('objetivo_base', models.TextField(blank=True, default='')),
                ('resultado_base', models.TextField(blank=True, default='')),
                ('instrucciones_ia', models.TextField(blank=True, default='')),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_predeterminada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='conceptoesperadoronda',
            name='regla_evaluacion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='configuracion_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='api_ia',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='esquema_ia_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='modelo_ia',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='respuesta_ia_estructurada',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='tokens_entrada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='tokens_salida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='api_ia',
            field=models.CharField(blank=True, default='responses', max_length=40),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='configuracion_bloqueada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='configuracion_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='esquema_ia_version',
            field=models.CharField(blank=True, default='rubrica-docente-v1', max_length=40),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='fecha_bloqueo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='metadata_generacion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='modelo_ia',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='prompt_version',
            field=models.CharField(blank=True, default='simuta-rubrica-v1', max_length=40),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='version_configuracion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='conceptoesperadoronda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('escenario__isnull', True), ('simulacion__isnull', False)), models.Q(('escenario__isnull', False), ('simulacion__isnull', True)), _connector='OR'), name='concepto_tiene_simulacion_o_escenario'),
        ),
        migrations.AddField(
            model_name='perfilmateriaia',
            name='materia_malla',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ia', to='academico.materiamalla'),
        ),
        migrations.AddField(
            model_name='perfilmateriaia',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='perfil_materia_ia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones', to='simulador.perfilmateriaia'),
        ),
        migrations.AddField(
            model_name='plantillaconcepto',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillaindicador',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillarestriccion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillaronda',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillaconcepto',
            name='ronda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='simulador.plantillaronda'),
        ),
        migrations.AddField(
            model_name='plantillasimulacion',
            name='materia_malla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_simulacion', to='academico.materiamalla'),
        ),
        migrations.AddField(
            model_name='plantillasimulacion',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plantillaronda',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='simulador.plantillasimulacion'),
        ),
        migrations.AddField(
            model_name='plantillarestriccion',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricciones', to='simulador.plantillasimulacion'),
        ),
        migrations.AddField(
            model_name='plantillaindicador',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='simulador.plantillasimulacion'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='plantilla_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones_generadas', to='simulador.plantillasimulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='plantillaconcepto',
            unique_together={('ronda', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillaronda',
            unique_together={('plantilla', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='plantillaindicador',
            unique_together={('plantilla', 'codigo')},
        ),
    ]
