# Generated by Django 6.0.6 on 2026-06-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0014_seed_global_template_and_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accionsugeridasimulacion',
            options={'ordering': ['simulacion', 'numero_ronda', 'texto']},
        ),
        migrations.AddField(
            model_name='accionsugeridasimulacion',
            name='numero_ronda',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantillaronda',
            name='opciones_decision',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
