# Generated by Django 6.0.6 on 2026-06-17 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0018_update_legacy_exam_simulations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacion',
            name='juego_contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PerfilJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('simulaciones_completadas', models.PositiveIntegerField(default=0)),
                ('racha_actual', models.PositiveIntegerField(default=0)),
                ('mejor_racha', models.PositiveIntegerField(default=0)),
                ('mejor_nota', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('insignias', models.JSONField(blank=True, default=list)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_juego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-xp_total'],
            },
        ),
    ]
