# Generated by Django 6.0.6 on 2026-06-17 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0019_intentosimulacion_juego_contabilizado_perfiljuego'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('ronda', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo_indicador_condicion', models.CharField(blank=True, default='', max_length=50)),
                ('operador_condicion', models.CharField(blank=True, choices=[('', 'Sin condicion'), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('=', '=')], default='', max_length=5)),
                ('valor_condicion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('efecto', models.JSONField(blank=True, default=dict)),
                ('prioridad', models.PositiveIntegerField(default=1)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'prioridad', 'ronda', 'nombre'],
            },
        ),
    ]
