# Generated by Django 6.0.6 on 2026-06-17 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0021_accionsugeridasimulacion_costo_recursos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizEvaluacionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('criterio', models.CharField(max_length=200)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evalua', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_caso', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'orden', 'criterio'],
            },
        ),
        migrations.CreateModel(
            name='OpcionCasoSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, default='', max_length=200)),
                ('valor_referencia', models.CharField(blank=True, default='', max_length=80)),
                ('fortaleza', models.TextField(blank=True, default='')),
                ('riesgo', models.TextField(blank=True, default='')),
                ('resultados', models.JSONField(blank=True, default=list)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_caso', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['simulacion', 'orden', 'nombre'],
            },
        ),
    ]
