# Generated by Django 6.0.6 on 2026-06-26 20:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_delete_silabomateria'),
        ('simulador', '0022_matrizevaluacioncaso_opcioncasosimulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('permite_reintento', models.BooleanField(default=True)),
                ('trabajo_en_equipo', models.BooleanField(default=False)),
                ('publicada', models.BooleanField(default=True)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos', to='simulador.asignacion'),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='simulador.asignacion')),
                ('integrantes', models.ManyToManyField(blank=True, related_name='equipos_simulacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asignacion', 'nombre'],
                'unique_together': {('asignacion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='intentosimulacion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos', to='simulador.equipo'),
        ),
        migrations.CreateModel(
            name='ResultadoAprendizaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('nivel_bloom', models.CharField(choices=[('RECORDAR', 'Recordar'), ('COMPRENDER', 'Comprender'), ('APLICAR', 'Aplicar'), ('ANALIZAR', 'Analizar'), ('EVALUAR', 'Evaluar'), ('CREAR', 'Crear')], default='APLICAR', max_length=20)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_aprendizaje', to='academico.materiamalla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resultado de aprendizaje',
                'verbose_name_plural': 'resultados de aprendizaje',
                'ordering': ['materia_malla', 'codigo'],
                'unique_together': {('materia_malla', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='conceptoesperadoronda',
            name='resultado_aprendizaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos', to='simulador.resultadoaprendizaje'),
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('paralelo', models.CharField(default='A', max_length=20)),
                ('estudiantes', models.ManyToManyField(blank=True, related_name='secciones_inscritas', to=settings.AUTH_USER_MODEL)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='academico.materiamalla')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='academico.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_dictadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['periodo', 'materia_malla__materia__nombre', 'paralelo'],
                'unique_together': {('materia_malla', 'periodo', 'paralelo')},
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='simulador.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('seccion', 'simulacion')},
        ),
    ]
