# Generated by Django 6.0.6 on 2026-06-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0023_asignacion_intentosimulacion_asignacion_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasosimulacion',
            name='reflexion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='reflexion_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
