# Generated by Django 6.0.6 on 2026-06-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0024_pasosimulacion_reflexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasosimulacion',
            name='pronostico_direccion',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='pronostico_indicador',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='pronostico_justificacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='pronostico_resultado',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
