# Generated by Django 6.0.6 on 2026-06-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0025_pasosimulacion_pronostico_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasosimulacion',
            name='tradeoff_aceptado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pasosimulacion',
            name='tradeoff_resultado',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
