# Generated by Django 6.0.6 on 2026-06-27 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0026_pasosimulacion_tradeoff_aceptado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetoRefuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('concepto', models.CharField(blank=True, default='', max_length=200)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('fecha_disponible', models.DateTimeField()),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_refuerzo', to=settings.AUTH_USER_MODEL)),
                ('intento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_refuerzo', to='simulador.intentosimulacion')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_refuerzo', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['completado', 'fecha_disponible', '-fecha_creacion'],
            },
        ),
    ]
