# Generated by Django 6.0.6 on 2026-08-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0027_retorefuerzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='peso_rubrica_decision',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cuanto de la nota de cada ronda mide COMO decide el estudiante (postura, evidencia del caso, trade-off y consecuencia medible) en vez de que conceptos del temario menciono. El resto lo aportan tus conceptos.', verbose_name='peso de la calidad de la decision (%)'),
        ),
    ]
