# Generated by Django 6.0.6 on 2026-08-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0028_simulacion_peso_rubrica_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='bonus_adaptacion',
            field=models.PositiveSmallIntegerField(default=6, help_text='Puntos extra si mejora de una ronda a la siguiente: premia corregir el rumbo, no solo acertar de entrada.', verbose_name='bonificacion por adaptarse (puntos)'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='bonus_pronostico',
            field=models.PositiveSmallIntegerField(default=8, help_text='Puntos extra si el estudiante anticipa correctamente hacia donde se movera un indicador antes de decidir. 0 lo desactiva.', verbose_name='bonificacion por pronosticar bien (puntos)'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='bonus_reflexion',
            field=models.PositiveSmallIntegerField(default=6, help_text='Puntos extra por escribir su reflexion despues de ver las consecuencias.', verbose_name='bonificacion por reflexionar (puntos)'),
        ),
    ]
