# Generated by Django 6.0.6 on 2026-08-04 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0029_simulacion_bonus_adaptacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intentosimulacion',
            name='investigaciones_compradas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='InvestigacionSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('sujeto', models.CharField(blank=True, default='', help_text='Sobre quien o que averigua: "Candidato B", "Proveedor Sur", "Segmento jovenes". Se usa para agrupar. Opcional.', max_length=120)),
                ('nombre', models.CharField(help_text='Lo que el estudiante ve antes de pagar: "Prueba tecnica".', max_length=200)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Que obtiene si la paga, sin revelar el hallazgo.')),
                ('hallazgo', models.TextField(help_text='Lo que se revela al pagarla. Aqui va la informacion oculta.')),
                ('costo_recursos', models.JSONField(blank=True, default=dict, help_text='Cuanto cuesta, por codigo de recurso. Ejemplo: {"presupuesto": 60}.')),
                ('disponible_desde_ronda', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigaciones', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investigacion',
                'verbose_name_plural': 'investigaciones',
                'ordering': ['simulacion', 'sujeto', 'orden', 'nombre'],
            },
        ),
    ]
