# Generated by Django 6.0.6 on 2026-08-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0046_reglas_disponibilidad_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='peso_resultado',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cuanto de la nota final depende de COMO QUEDO la empresa: si cumplio las condiciones de exito y como quedaron sus indicadores. Es lo que separa una simulacion de decisiones de un examen: con 0, el estudiante puede hundir el caso y aprobar igual si uso el vocabulario correcto.', verbose_name='peso del resultado del caso (%)'),
        ),
    ]
