# Generated by Django 6.0.6 on 2026-08-06 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_materiamallapredecesora_nivelperiodo_recordacademico'),
        ('simulador', '0048_opciones_farmaco_por_ronda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'ordering': ['periodo', 'materia_malla__materia__nombre', 'paralelo'], 'verbose_name': 'materia del periodo', 'verbose_name_plural': 'materias del periodo'},
        ),
        migrations.AddField(
            model_name='seccion',
            name='cupo',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='seccion',
            name='nivel_periodo',
            field=models.ForeignKey(blank=True, help_text='Oferta de nivel de la que salio. Vacio si la creo el profesor a mano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='academico.nivelperiodo'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secciones_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuiaApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=250)),
                ('tema', models.CharField(blank=True, max_length=250)),
                ('objetivo', models.TextField(blank=True, help_text='Que debe lograr el estudiante con la guia.')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('publicada', models.BooleanField(default=True)),
                ('resultado_aprendizaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='simulador.resultadoaprendizaje')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='simulador.seccion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'guia API',
                'verbose_name_plural': 'guias API',
                'ordering': ['seccion', 'numero'],
                'unique_together': {('seccion', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='guia_api',
            field=models.ForeignKey(blank=True, help_text='Guia API que evalua esta prueba.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='simulador.guiaapi'),
        ),
    ]
