# Generated by Django 6.0.6 on 2026-08-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_materiamallapredecesora_nivelperiodo_recordacademico'),
        ('simulador', '0049_alter_seccion_options_seccion_cupo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='academico.materiamalla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tema de materia',
                'verbose_name_plural': 'temas de materia',
                'ordering': ['materia_malla', 'orden', 'nombre'],
                'unique_together': {('materia_malla', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='ActividadMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('REFUERZO', 'Practicar y reforzar'), ('EVALUACION', 'Evaluar y aplicar')], max_length=20)),
                ('tipo', models.CharField(choices=[('SOPA_LETRAS', 'Sopa de letras'), ('MEMORIA', 'Memoria'), ('RELACIONAR', 'Relacionar conceptos'), ('ORDENAR', 'Ordenar procesos'), ('CUESTIONARIO', 'Cuestionario de practica'), ('CRUCIGRAMA', 'Crucigrama'), ('PRUEBA', 'Prueba'), ('EXAMEN_CORTO', 'Examen corto'), ('CASO_PRACTICO', 'Caso practico'), ('GUIA_APE', 'Guia APE'), ('PROYECTO', 'Proyecto integrador'), ('OTRO', 'Otra actividad')], max_length=30)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, upload_to='actividades_materia/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('materia_malla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.materiamalla')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, help_text='Vacio cuando la actividad abarca varios temas o toda la materia.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='simulador.temamateria')),
            ],
            options={
                'verbose_name': 'actividad de materia',
                'verbose_name_plural': 'actividades de materia',
                'ordering': ['materia_malla', 'tema__orden', 'categoria', 'orden', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='simulacion',
            name='tema_materia',
            field=models.ForeignKey(blank=True, help_text='Tema concreto de la materia. Vacio significa actividad general.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulaciones', to='simulador.temamateria'),
        ),
    ]
