# Generated by Django 6.0.6 on 2026-08-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0050_temamateria_actividadmateria_simulacion_tema_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacion',
            name='guia_api',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='cupo',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='nivel_periodo',
        ),
        migrations.DeleteModel(
            name='GuiaApi',
        ),
    ]
