# Generated by Django 6.0.6 on 2026-08-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0051_remove_asignacion_guia_api_remove_seccion_cupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadmateria',
            name='tipo',
            field=models.CharField(choices=[('PRUEBA', 'Prueba'), ('EXAMEN_CORTO', 'Examen corto'), ('CASO_PRACTICO', 'Caso practico'), ('GUIA_APE', 'Guia APE'), ('PROYECTO', 'Proyecto integrador'), ('OTRO', 'Otra actividad')], max_length=30),
        ),
    ]
