# Generated by Django 5.2.15 on 2026-08-08 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0052_alter_actividadmateria_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionsugeridasimulacion',
            name='puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cuanto vale, por si sola, elegir esta alternativa (0-100). Es lo que permite calificar sin IA: en un caso con respuesta correcta, elegir mal no puede puntuar igual que elegir bien. Vacio significa que la alternativa no puntua sola y la nota sale solo de la rubrica.', max_digits=5, null=True, verbose_name='puntaje de elegir esta alternativa'),
        ),
        migrations.AddField(
            model_name='accionsugeridasimulacion',
            name='retroalimentacion',
            field=models.TextField(blank=True, default='', help_text='Lo que se le dice al estudiante despues de elegirla.'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='modo_ejecucion',
            field=models.CharField(choices=[('CASO_INDEPENDIENTE', 'Decisiones independientes'), ('ARBOL_DECISION', 'Arbol de decisiones'), ('SIMULACION_ENCADENADA', 'Simulacion encadenada')], default='CASO_INDEPENDIENTE', help_text='Decisiones independientes: cada ronda es una situacion ya preparada y lo que el estudiante contesto en la ronda 1 no cambia la ronda 2. Es el caso normal. Arbol de decisiones: cada eleccion lleva a un escenario distinto. Simulacion encadenada: la decision mueve los indicadores y la siguiente ronda arranca con la empresa como quedo.', max_length=30, verbose_name='como se encadenan las rondas'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='ia_habilitada',
            field=models.BooleanField(default=True, help_text='Desactivalo cuando el caso ya trae respuesta correcta: puntaje por alternativa, valores esperados en los campos numericos y rubrica de conceptos. Asi se corrige con aritmetica y palabras clave, sin llamar a ningun proveedor. Es como funcionan los simuladores entregados por los docentes.', verbose_name='usar IA para evaluar lo que el estudiante escribe'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='tipo_simulacion',
            field=models.CharField(choices=[('SIN_IA_ARBOL', 'Sin IA - Arbol de decisiones'), ('CON_IA_DINAMICA', 'Con IA - Simulacion dinamica')], default='CON_IA_DINAMICA', max_length=30),
        ),
        migrations.CreateModel(
            name='RondaSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=250)),
                ('situacion', models.TextField(help_text='Lo que pasa en esta ronda y que tiene que resolver el estudiante.')),
                ('instrucciones', models.TextField(blank=True, default='')),
                ('datos', models.JSONField(blank=True, default=dict, help_text='Tablas y cifras del caso para esta ronda. Formato: {"tablas": [{"titulo": "...", "columnas": [...], "filas": [[...], ...]}], "formula": "...", "nota": "..."}.')),
                ('tipo_respuesta', models.CharField(choices=[('OPCION_UNICA', 'Elegir una alternativa'), ('OPCION_MULTIPLE', 'Elegir varias alternativas'), ('TEXTO', 'Responder por escrito'), ('NUMERICA', 'Calcular un valor'), ('ARCHIVO', 'Subir un archivo'), ('MIXTA', 'Varias cosas a la vez')], default='OPCION_UNICA', max_length=20)),
                ('campos', models.JSONField(blank=True, default=list, help_text='Lo que se le pide capturar, cuando no alcanza con elegir una alternativa. Cada campo: {"clave", "etiqueta", "tipo": "numero|texto|opcion", "objetivo", "tolerancia", "unidad"}.')),
                ('requiere_justificacion', models.BooleanField(default=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('respuesta_modelo', models.TextField(blank=True, default='', help_text='El desarrollo del docente. Se muestra al cerrar la ronda, para comparar.')),
                ('retroalimentacion', models.TextField(blank=True, default='')),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ronda del caso',
                'verbose_name_plural': 'rondas del caso',
                'ordering': ['simulacion', 'numero'],
                'unique_together': {('simulacion', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RecursoSimulacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('IMAGEN', 'Imagen'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('nombre', models.CharField(max_length=250)),
                ('archivo', models.FileField(blank=True, upload_to='simulaciones/archivos/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, default='')),
                ('vista_previa', models.ImageField(blank=True, help_text='Captura del archivo para mostrarla dentro del caso.', upload_to='simulaciones/preview/%Y/%m/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('simulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='simulador.simulacion')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('ronda', models.ForeignKey(blank=True, help_text='Vacio cuando el archivo sirve para todo el caso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='simulador.rondasimulacion')),
            ],
            options={
                'verbose_name': 'archivo del caso',
                'verbose_name_plural': 'archivos del caso',
                'ordering': ['simulacion', 'ronda__numero', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRondaSimulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('texto', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retroalimentacion', models.TextField(blank=True, default='')),
                ('impacto', models.JSONField(blank=True, default=dict, help_text='Solo en simulaciones encadenadas: {"codigo_indicador": variacion}.')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('ronda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='simulador.rondasimulacion')),
            ],
            options={
                'verbose_name': 'alternativa de la ronda',
                'verbose_name_plural': 'alternativas de la ronda',
                'ordering': ['ronda', 'orden', 'texto'],
            },
        ),
    ]
